name: phppackage/my-package
title: 'My Package'
description: ''
type: library
keywords: {  }
homepage: 'http://github.com/phppackage/my-package'
authors:
    - { name: '', email: '', homepage: 'http://github.com/phppackage/my-package', role: Owner }
autoload:
    psr-4: { phppackage\my-package\: src }
autoload-dev:
    psr-4: { phppackage\my-package\Tests\: tests }
vendor: phppackage
package: my-package
